<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#张量" data-toc-modified-id="张量-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>张量</a></span></li><li><span><a href="#计算图" data-toc-modified-id="计算图-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>计算图</a></span></li><li><span><a href="#自动微分" data-toc-modified-id="自动微分-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>自动微分</a></span></li><li><span><a href="#低阶API操作" data-toc-modified-id="低阶API操作-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>低阶<code>API</code>操作</a></span><ul class="toc-item"><li><span><a href="#张量操作" data-toc-modified-id="张量操作-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>张量操作</a></span><ul class="toc-item"><li><span><a href="#创建张量" data-toc-modified-id="创建张量-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>创建张量</a></span></li><li><span><a href="#索引切片" data-toc-modified-id="索引切片-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>索引切片</a></span></li><li><span><a href="#维度变化" data-toc-modified-id="维度变化-4.1.3"><span class="toc-item-num">4.1.3&nbsp;&nbsp;</span>维度变化</a></span></li><li><span><a href="#合并分割" data-toc-modified-id="合并分割-4.1.4"><span class="toc-item-num">4.1.4&nbsp;&nbsp;</span>合并分割</a></span></li></ul></li><li><span><a href="#张量运算" data-toc-modified-id="张量运算-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>张量运算</a></span><ul class="toc-item"><li><span><a href="#标量运算" data-toc-modified-id="标量运算-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>标量运算</a></span></li><li><span><a href="#向量运算" data-toc-modified-id="向量运算-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>向量运算</a></span></li><li><span><a href="#矩阵运算" data-toc-modified-id="矩阵运算-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>矩阵运算</a></span></li><li><span><a href="#广播机制" data-toc-modified-id="广播机制-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span>广播机制</a></span></li></ul></li><li><span><a href="#AutoGraph的使用" data-toc-modified-id="AutoGraph的使用-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span><code>AutoGraph</code>的使用</a></span><ul class="toc-item"><li><span><a href="#AutoGraph的使用规范" data-toc-modified-id="AutoGraph的使用规范-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span><code>AutoGraph</code>的使用规范</a></span></li><li><span><a href="#AutoGraph的机制原理" data-toc-modified-id="AutoGraph的机制原理-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span><code>AutoGraph</code>的机制原理</a></span></li><li><span><a href="#AutoGraph和tf.Module" data-toc-modified-id="AutoGraph和tf.Module-4.3.3"><span class="toc-item-num">4.3.3&nbsp;&nbsp;</span><code>AutoGraph</code>和<code>tf.Module</code></a></span></li><li><span><a href="#tf.keras.Model和tf.keras.layers.Layer" data-toc-modified-id="tf.keras.Model和tf.keras.layers.Layer-4.3.4"><span class="toc-item-num">4.3.4&nbsp;&nbsp;</span><code>tf.keras.Model</code>和<code>tf.keras.layers.Layer</code></a></span></li></ul></li></ul></li></ul></div>

In [1]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.0.0'

# 张量
- 张量和计算图是`TensorFlow`的核心概念；
- 张量即多维数组，与`Numpy`中的`array`类似
- 从行为特征来看，两种张量，`constant`和`Variable`，前者不可变，后者可以在计算图中用`assign`等算子重新赋值
    - 张量的数据类型！

In [2]:
a = tf.constant(1.23, dtype=tf.float32)
a

<tf.Tensor: id=0, shape=(), dtype=float32, numpy=1.23>

In [3]:
s = tf.constant("hello world")
s

<tf.Tensor: id=1, shape=(), dtype=string, numpy=b'hello world'>

In [4]:
b = tf.constant(True)
b

<tf.Tensor: id=2, shape=(), dtype=bool, numpy=True>

In [5]:
tensor3 = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0,
                                                               8.0]]])  # 3维张量
print(tensor3)

# 张量的秩
print(tf.rank(tensor3))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


In [6]:
# 改变张量的数据类型
a = tf.cast(a, tf.int32)
a

<tf.Tensor: id=5, shape=(), dtype=int32, numpy=1>

In [8]:
# 转化成Numpy数组
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [10]:
# 常量的重新赋值，创造新的内存空间
a = tf.constant([1.0, 2.0])
print(id(a))
a = a + tf.constant([1.0, 1.0])
print(id(a))

140464363546768
140464363546592


In [11]:
# 变量的值可以改变，可以通过assign, assign_add等方法给变量重新赋值
a = tf.Variable([1.0, 2.0], name='var')
print(id(a))
a.assign_add([1.0, 1.0])
print(a)
print(id(a))

140464360295888
<tf.Variable 'var:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
140464360295888


# 计算图
- `TensorFlow1.0`，采用的是**静态计算图**，需要先使用`TensorFlow`的各种算子创建计算图，然后再开启一个会话`Session`，显式执行计算图。
- `TensorFlow2.0`，采用的是**动态计算图**，即每使用一个算子后，该算子会被动态加入到隐含的默认计算图中立即执行得到结果，而无需开启`Session`。
    - 动态计算图即`Eager Excution`的好处是方便调试程序
    - 但是运行效率相对会低一些。因为使用动态图会有许多次`Python`进程和`TensorFlow`的`C++`进程之间的通信。
    - 而静态计算图构建完成之后几乎全部在`TensorFlow`内核上使用`C++`代码执行，效率更高
- 在`TensorFlow2.0`中使用静态图，可以使用`@tf.function`装饰器将普通Python函数转换成对应的`TensorFlow`计算图构建代码。该方法叫做`Autograph`.
    - 实践中，一般会先用动态计算图调试代码，然后在需要提高性能的的地方利用`@tf.function`切换成`Autograph`获得更高的效率。

In [13]:
# TensorFlow2.0中使用静态图，不推荐
g = tf.compat.v1.Graph()

# 定义计算图
with g.as_default():
    x = tf.compat.v1.placeholder(name='x', shape=[], dtype=tf.string)
    y = tf.compat.v1.placeholder(name='y', shape=[], dtype=tf.string)
    z = tf.strings.join([x, y], name="join", separator=" ")

# 执行计算图
with tf.compat.v1.Session(graph=g) as sess:
    result = sess.run(fetches=z, feed_dict={x: "hello", y: "world"})
    print(result)

b'hello world'


In [18]:
# 动态计算图
x = tf.constant("ehllo")
y = tf.constant('wordl')
z = tf.strings.join([x, y], separator=" ")
tf.print(z)

ehllo wordl


In [19]:
# 如果采用Autograph的方式使用计算图，
# 第一步定义计算图变成了定义函数，使用tf.function装饰
# 第二步执行计算图变成了调用函数，不需要使用with tf.Session
@tf.function
def strjoin(x, y):
    z = tf.strings.join([x, y], separator=" ")
    tf.print(z)
    return z


result = strjoin(tf.constant("hello"), tf.constant("world"))
print(result)

hello world
tf.Tensor(b'hello world', shape=(), dtype=string)


In [ ]:
import datetime

# 创建日志
stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'datasets/autograph/%s' % stamp
writer = tf.summary.create_file_writer(logdir)

#开启autograph跟踪
tf.summary.trace_on(graph=True, profiler=True)

#执行autograph
result = strjoin("hello", "world")

#将计算图信息写入日志
with writer.as_default():
    tf.summary.trace_export(name="autograph", step=0, profiler_outdir=logdir)

In [ ]:
# #启动 tensorboard在jupyter中的魔法命令
# %load_ext tensorboard

In [22]:
# #启动tensorboard
# %tensorboard --logdir datasets/autograph/

# 自动微分
- `tf.GradientTape`记录正向传播过程，并自动反向传播求梯度

In [24]:
# 求y=a*x^2+b*x+c的导数
x = tf.Variable(0.0, name="x", dtype=tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)

with tf.GradientTape() as tape:
    y = a * tf.pow(x, 2) + b * x + c
dy_dx = tape.gradient(y, x)
dy_dx

<tf.Tensor: id=209, shape=(), dtype=float32, numpy=-2.0>

In [28]:
# 对常量张量也可以求导，需要增加watch
with tf.GradientTape() as tape:
    tape.watch([a, b, c])
    y = a * tf.pow(x, 2) + b * x + c

dy_dx, dy_da, dy_db, dy_dc = tape.gradient(y, [x, a, b, c])
print(dy_da)
print(dy_dc)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [29]:
# 可以求二阶导数
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = a * tf.pow(x, 2) + b * x + c
    dy_dx = tape1.gradient(y, x)
dy2_dx2 = tape2.gradient(dy_dx, x)

print(dy2_dx2)

tf.Tensor(2.0, shape=(), dtype=float32)


In [30]:
# 可以在autograph中使用


@tf.function
def f(x):
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)

    # 自变量转换成tf.float32
    x = tf.cast(x, tf.float32)
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = a * tf.pow(x, 2) + b * x + c
    dy_dx = tape.gradient(y, x)

    return ((dy_dx, y))


tf.print(f(tf.constant(0.0)))
tf.print(f(tf.constant(1.0)))

(-2, 1)
(0, 0)


In [31]:
# 梯度下降求解y=a*x^2+b*x+c的最小值
x = tf.Variable(0.0, name="x", dtype=tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for _ in range(1000):
    with tf.GradientTape() as tape:
        y = a * tf.pow(x, 2) + b * x + c
    dy_dx = tape.gradient(y, x)
    optimizer.apply_gradients(grads_and_vars=[(dy_dx, x)])

tf.print("y=", y, "x=", x)

y= 0 x= 0.999998569


In [32]:
# 求f(x) = a*x**2 + b*x + c的最小值
# 使用optimizer.minimize
# optimizer.minimize相当于先用tape求gradient,再apply_gradient

x = tf.Variable(0.0, name="x", dtype=tf.float32)


#注意f()无参数
def f():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    y = a * tf.pow(x, 2) + b * x + c
    return (y)


optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for _ in range(1000):
    optimizer.minimize(f, [x])

tf.print("y =", f(), "; x =", x)

y = 0 ; x = 0.999998569


In [34]:
# 在autograph中完成最小值求解
# 使用optimizer.apply_gradients

x = tf.Variable(0.0, name="x", dtype=tf.float32)
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)


@tf.function
def minimizef():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)

    for _ in tf.range(1000):  #注意autograph时使用tf.range(1000)而不是range(1000)
        with tf.GradientTape() as tape:
            y = a * tf.pow(x, 2) + b * x + c
        dy_dx = tape.gradient(y, x)
        optimizer.apply_gradients(grads_and_vars=[(dy_dx, x)])

    y = a * tf.pow(x, 2) + b * x + c
    return y


tf.print(minimizef()), tf.print(x)

0
0.99999851


(None, None)

In [36]:
# 在autograph中完成最小值求解
# 使用optimizer.minimize

x = tf.Variable(0.0, name="x", dtype=tf.float32)
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)


@tf.function
def f():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    y = a * tf.pow(x, 2) + b * x + c
    return (y)


@tf.function
def train(epoch):
    for _ in tf.range(epoch):
        optimizer.minimize(f, [x])
    return (f())


tf.print(train(1000)), tf.print(x)

0
0.99999851


(None, None)

# 低阶`API`操作

## 张量操作

### 创建张量

In [37]:
# 通过列表
a = tf.constant([1, 2, 3], dtype=tf.float32)
tf.print(a)

[1 2 3]


In [38]:
# range函数
b = tf.range(1, 10, delta=2)
tf.print(b)

[1 3 5 7 9]


In [39]:
# 函数
c = tf.linspace(0.0, 2 * 3.14, 100)
tf.print(c)

[0 0.0634343475 0.126868695 ... 6.15313148 6.21656609 6.28]


In [40]:
# 函数
d = tf.zeros([3, 3])
tf.print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
# 函数
a = tf.ones([3, 3])
b = tf.zeros_like(a, dtype=tf.float32)
tf.print(a)
tf.print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [42]:
b = tf.fill([3, 2], 5)
tf.print(b)

[[5 5]
 [5 5]
 [5 5]]


In [43]:
# 均匀分布随机
tf.random.set_seed(1.0)
a = tf.random.uniform([5], minval=0, maxval=10)
tf.print(a)

[1.65130854 9.01481247 6.30974197 4.34546089 2.9193902]


In [44]:
# 正态分布随机
b = tf.random.normal([3, 3], mean=0.0, stddev=1.0)
tf.print(b)

[[0.403087884 -1.0880208 -0.0630953535]
 [1.33655667 0.711760104 -0.489286453]
 [-0.764221311 -1.03724861 -1.25193381]]


In [45]:
# 截断正态分布随机
c = tf.random.truncated_normal((5, 5), mean=0.0, stddev=1.0, dtype=tf.float32)
tf.print(c)

[[-0.457012206 -0.406867266 0.728577793 -0.892977774 -0.369404584]
 [0.323488563 1.19383323 0.888298929 1.25985587 -1.95951891]
 [-0.202244401 0.294496894 -0.468728036 1.29494202 1.48142183]
 [0.0810953453 1.63843894 0.556645 0.977199852 -1.17777884]
 [1.67368948 0.0647980496 -0.705142677 -0.281972557 0.126546144]]


In [46]:
# 特殊矩阵
I = tf.eye(3, 3)  #单位矩阵
tf.print(I)

t = tf.linalg.diag([1, 2, 3])  #对角阵
tf.print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 索引切片
- `tf.slice,tf.gather,tf.gather_nd,tf.boolean_mask`
- `tf.where,tf.scatter_nd`

In [47]:
tf.random.set_seed(3)
t = tf.random.uniform([5, 5], minval=0, maxval=10, dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [48]:
# 第0行
tf.print(t[0])

# 最后一行
tf.print(t[-1])

[4 7 4 2 9]
[3 7 0 0 3]


In [49]:
# 第1行第3列
tf.print(t[1, 3])
tf.print(t[1][3])

4
4


In [50]:
# 第1行到第3行
tf.print(t[1:4, :])
tf.print(tf.slice(t, [1, 0], [3, 5]))  # (input,begin_vector,size_vector)

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]
[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]


In [52]:
# 第1到最后一行，间隔一列
tf.print(t[1:4, ::2])

[[9 2 7]
 [7 7 0]
 [9 9 2]]


In [53]:
# 修改变量的元素
x = tf.Variable([[1, 2], [3, 4]], dtype=tf.float32)
x[1, :].assign(tf.constant([0.0, 0.0]))
tf.print(x)

[[1 2]
 [0 0]]


In [54]:
# 省略号可以表示多个冒号
tf.print(t[..., 1])

[7 1 2 6 7]


In [56]:
# 不规则切片
# 4个班级，每个班级10个学生，每个学生10门课
scores = tf.random.uniform((4, 10, 7), minval=0, maxval=100, dtype=tf.int32)

# 每个班级，第0、5、9个学生的score
p = tf.gather(scores, [0, 5, 9], axis=1)
tf.print(p)

# 第1、3、6门课的score
q = tf.gather(tf.gather(scores, [0, 5, 9], axis=1), [1, 3, 6], axis=2)
tf.print(q)

[[[52 82 66 ... 17 86 14]
  [24 80 70 ... 72 63 96]
  [24 99 38 ... 97 44 74]]

 [[79 73 73 ... 35 3 81]
  [46 10 94 ... 23 18 92]
  [0 21 89 ... 53 10 90]]

 [[52 80 22 ... 29 25 60]
  [19 12 23 ... 87 86 25]
  [61 78 70 ... 7 59 21]]

 [[56 57 45 ... 23 15 3]
  [6 41 79 ... 97 43 13]
  [71 27 44 ... 0 52 16]]]
[[[82 55 14]
  [80 46 96]
  [99 58 74]]

 [[73 48 81]
  [10 38 92]
  [21 86 90]]

 [[80 57 60]
  [12 34 25]
  [78 71 21]]

 [[57 75 3]
  [41 47 13]
  [27 96 16]]]


In [58]:
# 指定坐标，0班级0学生、2班级4学生、3班级6学生
s = tf.gather_nd(scores, indices=[(0, 0), (2, 4), (3, 6)])
tf.print(s)

[[52 82 66 ... 17 86 14]
 [99 94 46 ... 1 63 41]
 [46 83 70 ... 90 85 17]]


In [59]:
# tf.gather和tf.gather_dn也可以通过tf.boolean_mask实现
p = tf.boolean_mask(
    scores,
    [True, False, False, False, False, True, False, False, False, True],
    axis=1)
tf.print(p)

[[[52 82 66 ... 17 86 14]
  [24 80 70 ... 72 63 96]
  [24 99 38 ... 97 44 74]]

 [[79 73 73 ... 35 3 81]
  [46 10 94 ... 23 18 92]
  [0 21 89 ... 53 10 90]]

 [[52 80 22 ... 29 25 60]
  [19 12 23 ... 87 86 25]
  [61 78 70 ... 7 59 21]]

 [[56 57 45 ... 23 15 3]
  [6 41 79 ... 97 43 13]
  [71 27 44 ... 0 52 16]]]


In [60]:
s = tf.boolean_mask(
    scores,
    [[True, False, False, False, False, False, False, False, False, False],
     [False, False, False, False, False, False, False, False, False, False],
     [False, False, False, False, True, False, False, False, False, False],
     [False, False, False, False, False, False, True, False, False, False]])
tf.print(s)

[[52 82 66 ... 17 86 14]
 [99 94 46 ... 1 63 41]
 [46 83 70 ... 90 85 17]]


In [61]:
# 利用tf.boolean_mask可以实现布尔索引

# 找到矩阵中小于0的元素
c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype=tf.float32)
tf.print(c, "\n")

tf.print(tf.boolean_mask(c, c < 0), "\n")
tf.print(c[c < 0])  # 布尔索引，为boolean_mask的语法糖形式

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 

[-1 -1 -2 -3] 

[-1 -1 -2 -3]


In [62]:
# 找到张量中小于0的元素,将其换成np.nan得到新的张量
# tf.where和np.where作用类似

c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype=tf.float32)
d = tf.where(c < 0, tf.fill(c.shape, np.nan), c)
d

<tf.Tensor: id=48802, shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [64]:
# 如果where只有一个参数，将返回所有满足条件的位置坐标
indices = tf.where(c < 0)
indices

<tf.Tensor: id=48809, shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [65]:
# 将张量的第[0,0]和[2,1]两个位置元素替换为0得到新的张量
d = c - tf.scatter_nd([[0, 0], [2, 1]], [c[0, 0], c[2, 1]], c.shape)
d

<tf.Tensor: id=48824, shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3.,  0.,  3.]], dtype=float32)>

In [68]:
?tf.scatter_nd

In [69]:
# scatter_nd的作用和gather_nd有些相反
# 可以将某些值插入到一个给定shape的全0的张量的指定位置处。
indices = tf.where(c<0)
tf.scatter_nd(indices,tf.gather_nd(c,indices),c.shape)

<tf.Tensor: id=48836, shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

### 维度变化
- `tf.reshape`
- `tf.squeeze`
- `tf.expand_dims`
- `tf.transpose`

In [70]:
a = tf.random.uniform(shape=[1, 3, 3, 2], minval=0, maxval=255, dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[100 44]
   [181 14]
   [90 53]]

  [[205 141]
   [14 24]
   [239 46]]

  [[225 174]
   [212 78]
   [14 144]]]]


In [71]:
# 改成 （3,6）形状的张量
b = tf.reshape(a, [3, 6])
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[100 44 181 14 90 53]
 [205 141 14 24 239 46]
 [225 174 212 78 14 144]]


In [72]:
# 改回成 [1,3,3,2] 形状的张量
c = tf.reshape(b, [1, 3, 3, 2])
tf.print(c)

[[[[100 44]
   [181 14]
   [90 53]]

  [[205 141]
   [14 24]
   [239 46]]

  [[225 174]
   [212 78]
   [14 144]]]]


In [73]:
# 删除只有一个元素的维度
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[100 44]
  [181 14]
  [90 53]]

 [[205 141]
  [14 24]
  [239 46]]

 [[225 174]
  [212 78]
  [14 144]]]


In [75]:
# 增加维度，在第0维插入长度为1的一个维度
d = tf.expand_dims(s, axis=1)
tf.print(d.shape)
tf.print(d)

TensorShape([3, 1, 3, 2])
[[[[100 44]
   [181 14]
   [90 53]]]


 [[[205 141]
   [14 24]
   [239 46]]]


 [[[225 174]
   [212 78]
   [14 144]]]]


In [76]:
# 交换张量的维度，与tf.reshape不同，它会改变张量元素的存储顺序。
# tf.transpose常用于图片存储格式的变换上

# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100, 600, 600, 4],
                      minval=0,
                      maxval=255,
                      dtype=tf.int32)
tf.print(a.shape)

# 转换成 Channel,Height,Width,Batch
s = tf.transpose(a, perm=[3, 1, 2, 0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


### 合并分割
- `tf.concat`
- `tf.stack`
- `tf.split`

In [78]:
# tf.concat拼接，不会增加维度
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
c = tf.constant([[9.0, 10.0], [11.0, 12.0]])

tf.concat([a, b, c], axis=1)

<tf.Tensor: id=48896, shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  5.,  6.,  9., 10.],
       [ 3.,  4.,  7.,  8., 11., 12.]], dtype=float32)>

In [80]:
# tf.stack堆叠，会增加新的维度
tf.stack([a, b, c], axis=1)

<tf.Tensor: id=48902, shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]],

       [[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]], dtype=float32)>

In [81]:
# tf.split(value,num_or_size_splits,axis)
# tf.concat 的逆运算

a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
c = tf.constant([[9.0, 10.0], [11.0, 12.0]])
c = tf.concat([a, b, c], axis=0)

tf.split(c, 3, axis=0)  #指定分割份数，平均分割

[<tf.Tensor: id=48912, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: id=48913, shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: id=48914, shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [82]:
tf.split(c, [1, 2, 3], axis=0)  #指定每份的记录数量

[<tf.Tensor: id=48919, shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>,
 <tf.Tensor: id=48920, shape=(2, 2), dtype=float32, numpy=
 array([[3., 4.],
        [5., 6.]], dtype=float32)>,
 <tf.Tensor: id=48921, shape=(3, 2), dtype=float32, numpy=
 array([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]], dtype=float32)>]

## 张量运算

### 标量运算
- 对张量实施逐元素运算

In [84]:
a = tf.constant([[1.0, 2], [-3, 4.0]])
b = tf.constant([[5.0, 6], [7.0, 8.0]])
tf.print(a + b)
tf.print(a / b)
tf.print(a * b)
tf.print(a % 3)
tf.print(a >= 2)
tf.print((a >= 2) & (a <= 3))

[[6 8]
 [4 12]]
[[0.2 0.333333343]
 [-0.428571433 0.5]]
[[5 12]
 [-21 32]]
[[1 2]
 [-0 1]]
[[0 1]
 [0 1]]
[[0 1]
 [0 0]]


### 向量运算
- 在指定的轴上运算，先将两个向量广播成相同的维度，很多以`reduce`开头

In [86]:
# 向量reduce
a = tf.range(1, 10)
tf.print(tf.reduce_sum(a))
tf.print(tf.reduce_mean(a))
tf.print(tf.reduce_max(a))
tf.print(tf.reduce_min(a))
tf.print(tf.reduce_prod(a))

45
5
9
1
362880


In [87]:
# 张量指定维度进行reduce
b = tf.reshape(a, (3, 3))
tf.print(tf.reduce_sum(b, axis=1, keepdims=True))
tf.print(tf.reduce_sum(b, axis=0, keepdims=True))

[[6]
 [15]
 [24]]
[[12 15 18]]


In [88]:
# bool类型的reduce
p = tf.constant([True, False, False])
q = tf.constant([False, False, True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

0
1


In [89]:
# 利用tf.foldr实现tf.reduce_sum
s = tf.foldr(lambda a, b: a + b, tf.range(10))
tf.print(s)

45


In [90]:
# cum扫描累积
a = tf.range(1, 10)
tf.print(tf.math.cumsum(a))
tf.print(tf.math.cumprod(a))

[1 3 6 ... 28 36 45]
[1 2 6 ... 5040 40320 362880]


In [91]:
# arg最大最小值索引
a = tf.range(1, 10)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))

8
0


In [92]:
#tf.math.top_k可以用于对张量排序
a = tf.constant([1, 3, 7, 5, 4, 8])

values, indices = tf.math.top_k(a, 3, sorted=True)
tf.print(values)
tf.print(indices)

[8 7 5]
[5 2 3]


### 矩阵运算
- 矩阵乘法，矩阵转置，矩阵逆，矩阵求迹，矩阵范数，矩阵行列式，矩阵求特征值，矩阵分解等运算
- `tf.linalg`

In [93]:
# 矩阵乘法
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[2, 0], [0, 2]])
tf.print(a @ b)  # 等价于tf.matmul(a,b)
tf.matmul(a, b)

[[2 4]
 [6 8]]


<tf.Tensor: id=49101, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [97]:
# 矩阵转置
a = tf.constant([[1.0, 2], [3, 4], [5.0, 7.]])
tf.transpose(a)

<tf.Tensor: id=49111, shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 5.],
       [2., 4., 7.]], dtype=float32)>

In [98]:
# 矩阵逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0, 2], [3.0, 4]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: id=49115, shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [99]:
# 矩阵求trace
a = tf.constant([[1.0, 2], [3, 4]])
tf.linalg.trace(a)

<tf.Tensor: id=49121, shape=(), dtype=float32, numpy=5.0>

In [100]:
# 矩阵求范数
a = tf.constant([[1.0, 2], [3, 4]])
tf.linalg.norm(a)

<tf.Tensor: id=49129, shape=(), dtype=float32, numpy=5.477226>

In [101]:
# 矩阵行列式
a = tf.constant([[1.0, 2], [3, 4]])
tf.linalg.det(a)

<tf.Tensor: id=49133, shape=(), dtype=float32, numpy=-2.0>

In [102]:
# 矩阵特征值
tf.linalg.eigvalsh(a)

<tf.Tensor: id=49136, shape=(2,), dtype=float32, numpy=array([-0.854102,  5.854102], dtype=float32)>

In [103]:
# 矩阵qr分解
a = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
q, r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q @ r)

[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227734]]
[[-3.1622777 -4.4271884]
 [0 -0.632455349]]
[[1.00000012 1.99999976]
 [3 4]]


In [104]:
# 矩阵svd分解
a = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
v, s, d = tf.linalg.svd(a)
tf.matmul(tf.matmul(s, tf.linalg.diag(v)), d)

<tf.Tensor: id=49155, shape=(2, 2), dtype=float32, numpy=
array([[ 1.5471475, -1.6144147],
       [ 2.757959 , -4.1705713]], dtype=float32)>

### 广播机制
TensorFlow的广播规则和numpy是一样的:
1. 如果张量的维度不同，将维度较小的张量进行扩展，直到两个张量的维度都一样。
2. 如果两个张量在某个维度上的长度是相同的，或者其中一个张量在该维度上的长度为1，那么我们就说这两个张量在该维度上是相容的。
3. 如果两个张量在所有维度上都是相容的，它们就能使用广播。
4. 广播之后，每个维度的长度将取两个张量在该维度长度的较大值。
5. 在任何一个维度上，如果一个张量的长度为1，另一个张量长度大于1，那么在该维度上，就好像是对第一个张量进行了复制。

`tf.broadcast_to` 以显式的方式按照广播机制扩展张量的维度。

In [105]:
a = tf.constant([1, 2, 3])
b = tf.constant([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
b + a  #等价于 b + tf.broadcast_to(a,b.shape)

<tf.Tensor: id=49160, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [107]:
a = tf.broadcast_to(a, b.shape)
tf.print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## `AutoGraph`的使用

### `AutoGraph`的使用规范

- 被`@tf.function`修饰的函数应尽可能使用`TensorFlow`函数而不是Python中的其他函数。例如使用`tf.print`而不是`print`，使用`tf.range`而不是`range`，使用`tf.constant(True)`而不是`True`.
    
   
- 避免在`@tf.function`修饰的函数内部定义`tf.Variable`.
      
        
- 被`@tf.function`修饰的函数不可修改该函数外部的`Python`列表或字典等数据结构变量

In [108]:
# 尽可能修饰TensorFlow函数

@tf.function
def np_random():
    a = np.random.randn(3, 3)
    tf.print(a)


@tf.function
def tf_random():
    a = tf.random.normal((3, 3))
    tf.print(a)

In [109]:
# np_random每次执行结果相同
np_random()
np_random()

array([[-0.03548311,  0.54931532,  0.55416616],
       [ 0.75196448, -0.4719244 ,  1.22372603],
       [ 0.5938145 ,  0.88359098,  1.6185849 ]])
array([[-0.03548311,  0.54931532,  0.55416616],
       [ 0.75196448, -0.4719244 ,  1.22372603],
       [ 0.5938145 ,  0.88359098,  1.6185849 ]])


In [110]:
# tf_random每次执行都会有重新生成随机数。
tf_random()
tf_random()

[[-1.50728667 -0.852984726 -0.784401238]
 [-0.265477121 0.73242414 0.334128559]
 [-0.36110726 1.34450936 -2.46136665]]
[[-2.63817787 -0.871187329 -0.618899286]
 [0.102082871 -1.47540975 -1.27701926]
 [0.0411223136 0.963910043 0.184175834]]


In [111]:
# 避免在@tf.function修饰的函数内部定义tf.Variable.

x = tf.Variable(1.0, dtype=tf.float32)


@tf.function
def outer_var():
    x.assign_add(1.0)
    tf.print(x)
    return (x)


outer_var()
outer_var()

2
3


<tf.Tensor: id=49210, shape=(), dtype=float32, numpy=3.0>

In [112]:
@tf.function
def inner_var():
    x = tf.Variable(1.0,dtype = tf.float32)
    x.assign_add(1.0)
    tf.print(x)
    return(x)

# 执行将报错
inner_var()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


ValueError: in converted code:

    <ipython-input-112-5a1a4a35ee7e>:3 inner_var  *
        x = tf.Variable(1.0,dtype = tf.float32)
    /home/yangbin7/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py:260 __call__
        return cls._variable_v2_call(*args, **kwargs)
    /home/yangbin7/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py:254 _variable_v2_call
        shape=shape)
    /home/yangbin7/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py:65 getter
        return captured_getter(captured_previous, **kwargs)
    /home/yangbin7/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py:413 invalid_creator_scope
        "tf.function-decorated function tried to create "

    ValueError: tf.function-decorated function tried to create variables on non-first call.


In [113]:
tensor_list = []


#@tf.function #加上这一行切换成Autograph结果将不符合预期！！！
def append_tensor(x):
    tensor_list.append(x)
    return tensor_list


append_tensor(tf.constant(5.0))
append_tensor(tf.constant(6.0))
print(tensor_list)

[<tf.Tensor: id=49250, shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: id=49251, shape=(), dtype=float32, numpy=6.0>]


In [114]:
tensor_list = []


@tf.function  #加上这一行切换成Autograph结果将不符合预期！！！
def append_tensor(x):
    tensor_list.append(x)
    return tensor_list


append_tensor(tf.constant(5.0))
append_tensor(tf.constant(6.0))
print(tensor_list)

[<tf.Tensor 'x:0' shape=() dtype=float32>]


### `AutoGraph`的机制原理

In [118]:
import tensorflow as tf
import numpy as np


@tf.function(autograph=True)
def myadd(a, b):
    for i in tf.range(3):
        tf.print(i)
    c = a + b
    print("tracing")
    return c

In [119]:
myadd(tf.constant("hello"), tf.constant("world"))

tracing
0
1
2


<tf.Tensor: id=49414, shape=(), dtype=string, numpy=b'helloworld'>

当**第一次调用**这个被`@tf.function`装饰的函数时
- 创建计算图:
    - 即创建一个静态计算图，跟踪执行一遍函数体中的Python代码，确定各个变量的Tensor类型，并根据执行顺序将算子添加到计算图中。 在这个过程中，如果开启了`autograph=True`(默认开启),会将Python控制流转换成`TensorFlow`图内控制流。 主要是将if语句转换成 `tf.cond`算子表达，将`while`和`for`循环语句转换成`tf.while_loop`算子表达，并在必要的时候添加 `tf.control_dependencies`指定执行顺序依赖关系。
    
> 等价于`tensorflow1.0`：
```
g = tf.Graph()
with g.as_default():
    a = tf.placeholder(shape=[],dtype=tf.string)
    b = tf.placeholder(shape=[],dtype=tf.string)
    cond = lambda i: i<tf.constant(3)
    def body(i):
        tf.print(i)
        return(i+1)
    loop = tf.while_loop(cond,body,loop_vars=[0])
    loop
    with tf.control_dependencies(loop):
        c = tf.strings.join([a,b])
    print("tracing")
```


- 执行计算图:

> 等价于`tensorflow1.0`：
```
with tf.Session(graph=g) as sess:
    sess.run(c,feed_dict={a:tf.constant("hello"),b:tf.constant("world")})
```    

In [120]:
myadd(tf.constant("hello"), tf.constant("again"))
# 再次调用，输出不打印 print("tracing")

0
1
2


<tf.Tensor: id=49419, shape=(), dtype=string, numpy=b'helloagain'>

当**再次调用**相同的函数时，且输入参数为与上次调用相同类型的`Tensor`时，直接执行计算图
- 当传参不为`TensorFlow`的`Tensor`类型时，每次都会重新创建新的计算图再执行

In [121]:
myadd(tf.constant(1), tf.constant(1000))
# 与上次调用传参不同，上次为字符串，此次为数值类型的Tensor，重建计算图

tracing
0
1
2


<tf.Tensor: id=49469, shape=(), dtype=int32, numpy=1001>

In [122]:
myadd(tf.constant(1), tf.constant(1000))
# 与上次相同的数值类型Tensor，直接执行

0
1
2


<tf.Tensor: id=49474, shape=(), dtype=int32, numpy=1001>

1. 被`@tf.function`修饰的函数应尽量使用`TensorFlow`中的函数而不是`Python`中的其他函数。例如使用`tf.print`而不是`print`.
    - 解释：`Python`中的函数仅仅会在跟踪执行函数以创建静态图的阶段使用，普通`Python`函数是无法嵌入到静态计算图中的，所以 在计算图构建好之后再次调用的时候，这些`Python`函数并没有被计算，而`TensorFlow`中的函数则可以嵌入到计算图中。使用普通的`Python`函数会导致 被`@tf.function`修饰前【eager执行】和被`@tf.function`修饰后【静态图执行】的输出不一致。
   
  
2. 避免在`@tf.function`修饰的函数内部定义`tf.Variable`.
    - 解释：如果函数内部定义了`tf.Variable`,那么在【eager执行】时，这种创建`tf.Variable`的行为在每次函数调用时候都会发生。但是在【静态图执行】时，这种创建`tf.Variable`的行为只会发生在第一步跟踪`Python`代码逻辑创建计算图时，这会导致被`@tf.function`修饰前【eager执行】和被`@tf.function`修饰后【静态图执行】的输出不一致。实际上，TensorFlow在这种情况下一般会报错。
               
                
3. 被`@tf.function`修饰的函数不可修改该函数外部的`Python`列表或字典等数据结构变量。
    - 解释：静态计算图是被编译成C++代码在TensorFlow内核中执行的。Python中的列表和字典等数据结构变量是无法嵌入到计算图中，它们仅仅能够在创建计算图时被读取，在执行计算图时是无法修改`Python`中的列表或字典这样的数据结构变量的。

### `AutoGraph`和`tf.Module`

 - 构建`Autograph`时应该避免在`@tf.function`修饰的函数内部定义`tf.Variable`.但是如果在函数外部定义`tf.Variable`的话，又会显得这个函数有外部变量依赖，封装不够完美。
 - `TensorFlow`提供了一个基类`tf.Module`，通过继承它构建子类，可以非常方便地管理变量
     - `tf.keras.models.Model`,`tf.keras.layers.Layer` 都是继承自`tf.Module`的

In [17]:
import tensorflow as tf
import numpy as np

x = tf.Variable(1.0, dtype=tf.float32)


#在tf.function中用input_signature限定输入张量的签名类型：shape和dtype
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32)])
def add_print(a):
    x.assign_add(a)
    tf.print(x)
    return x

In [18]:
add_print(tf.constant(3.0))
# add_print(tf.constant(3)) #输入不符合张量签名的参数将报错

4


<tf.Tensor: id=284, shape=(), dtype=float32, numpy=4.0>

In [19]:
add_print(tf.constant(3.0))
# 外部变量，每次调用都更新

7


<tf.Tensor: id=288, shape=(), dtype=float32, numpy=7.0>

In [20]:
# 利用tf.Module的子类化将其封装
class DemoModule(tf.Module):
    def __init__(self, init_value=tf.constant(0.0), name=None):
        super(DemoModule, self).__init__(name=name)
        # 相当于with tf.name_scope("demo_module")
        with self.name_scope:
            self.x = tf.Variable(init_value, dtype=tf.float32, trainable=True)

    @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32)])
    def addprint(self, a):
        with self.name_scope:
            self.x.assign_add(a)
            tf.print(self.x)
            return (self.x)

In [21]:
# 执行
demo = DemoModule(init_value=tf.constant(1.0))
result = demo.addprint(tf.constant(5.0))

6


In [22]:
# 再次执行
result = demo.addprint(tf.constant(5.0))

11


In [23]:
# 查看模块中的全部变量和全部可训练变量
print(demo.variables)
print(demo.trainable_variables)

(<tf.Variable 'demo_module/Variable:0' shape=() dtype=float32, numpy=11.0>,)
(<tf.Variable 'demo_module/Variable:0' shape=() dtype=float32, numpy=11.0>,)


In [24]:
# 查看模块中的全部子模块
demo.submodules

()

In [25]:
# 使用tf.saved_model 保存模型，并指定需要跨平台部署的方法
tf.saved_model.save(demo,
                    "datasets/demo/1",
                    signatures={"serving_default": demo.addprint})

INFO:tensorflow:Assets written to: datasets/demo/1/assets


In [26]:
# 加载模型
demo2 = tf.saved_model.load("datasets/demo/1")
demo2.addprint(tf.constant(5.0))

16


<tf.Tensor: id=478, shape=(), dtype=float32, numpy=16.0>

In [27]:
!saved_model_cli show --dir datasets/demo/1 --all


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['a'] tensor_info:
        dtype: DT_FLOAT
        shape: ()
        name: serving_default_a:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: ()
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict


在`tensorboard`中查看计算图，模块会被添加模块名`demo_module`,方便层次化呈现计算图结构。

In [28]:
import datetime

# 创建日志
stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'datasets/demomodule/%s' % stamp
writer = tf.summary.create_file_writer(logdir)

#开启autograph跟踪
tf.summary.trace_on(graph=True, profiler=True) 

#执行autograph
demo = DemoModule(init_value = tf.constant(0.0))
result = demo.addprint(tf.constant(5.0))

#将计算图信息写入日志
with writer.as_default():
    tf.summary.trace_export(
        name="demomodule",
        step=0,
        profiler_outdir=logdir)
    

5


In [ ]:
#启动 tensorboard在jupyter中的魔法命令
%reload_ext tensorboard

from tensorboard import notebook
notebook.list() 

notebook.start("--logdir datasets/demomodule/")

除了利用`tf.Module`的子类化实现封装，我们也可以通过给`tf.Module`添加属性的方法进行封装。

In [29]:
mymodule = tf.Module()
mymodule.x = tf.Variable(0.0)


@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32)])
def addprint(a):
    mymodule.x.assign_add(a)
    tf.print(mymodule.x)
    return (mymodule.x)


mymodule.addprint = addprint

In [30]:
mymodule.addprint(tf.constant(1.0)).numpy()

1


1.0

In [ ]:
#使用tf.saved_model 保存模型
tf.saved_model.save(mymodule,
                    "datasets/mymodule",
                    signatures={"serving_default": mymodule.addprint})

#加载模型
mymodule2 = tf.saved_model.load("datasets/mymodule")
mymodule2.addprint(tf.constant(5.0))

### `tf.keras.Model`和`tf.keras.layers.Layer`
都是继承自`tf.Module`实现的，也具有变量管理和子模块管理功能。

In [31]:
import tensorflow as tf
from tensorflow.keras import models, layers, losses, metrics

In [32]:
print(issubclass(tf.keras.Model, tf.Module))
print(issubclass(tf.keras.layers.Layer, tf.Module))
print(issubclass(tf.keras.Model, tf.keras.layers.Layer))

True
True
True


In [33]:
tf.keras.backend.clear_session()

model = models.Sequential()

model.add(layers.Dense(4, input_shape=(10, )))
model.add(layers.Dense(2))
model.add(layers.Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(10, 4) dtype=float32, numpy=
 array([[-0.45469707,  0.18753701, -0.5959868 ,  0.6175827 ],
        [-0.38891506,  0.30182558,  0.08736479,  0.1937024 ],
        [-0.2026245 , -0.17742622, -0.6446443 ,  0.0100345 ],
        [-0.28558233,  0.32829142, -0.4681566 ,  0.49711895],
        [-0.3520099 , -0.31394392,  0.44839418,  0.21992254],
        [-0.4661494 ,  0.05684429,  0.13205594,  0.19624263],
        [ 0.0440222 ,  0.56892383,  0.5804639 , -0.39511964],
        [-0.11376911,  0.56682813,  0.4243778 ,  0.33853883],
        [-0.6357041 ,  0.05275154, -0.16149044,  0.56283355],
        [ 0.2299828 ,  0.48133743, -0.43574002,  0.26523775]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.40421462, -0.66200423],
        [-0.95637345,  0.7510748 ],
        [ 0.16754365, -0.42345142],
        [-

In [35]:
model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(10, 4) dtype=float32, numpy=
 array([[-0.45469707,  0.18753701, -0.5959868 ,  0.6175827 ],
        [-0.38891506,  0.30182558,  0.08736479,  0.1937024 ],
        [-0.2026245 , -0.17742622, -0.6446443 ,  0.0100345 ],
        [-0.28558233,  0.32829142, -0.4681566 ,  0.49711895],
        [-0.3520099 , -0.31394392,  0.44839418,  0.21992254],
        [-0.4661494 ,  0.05684429,  0.13205594,  0.19624263],
        [ 0.0440222 ,  0.56892383,  0.5804639 , -0.39511964],
        [-0.11376911,  0.56682813,  0.4243778 ,  0.33853883],
        [-0.6357041 ,  0.05275154, -0.16149044,  0.56283355],
        [ 0.2299828 ,  0.48133743, -0.43574002,  0.26523775]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.40421462, -0.66200423],
        [-0.95637345,  0.7510748 ],
        [ 0.16754365, -0.42345142],
        [-

In [36]:
model.layers[0].trainable = False  #冻结第0层的变量,使其不可训练
model.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.40421462, -0.66200423],
        [-0.95637345,  0.7510748 ],
        [ 0.16754365, -0.42345142],
        [-0.9802644 , -0.53516245]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.8734658],
        [ 1.4005286]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [37]:
model.submodules

(<tensorflow.python.keras.engine.input_layer.InputLayer at 0x7fc93c059c90>,
 <tensorflow.python.keras.layers.core.Dense at 0x7fc93c03d9d0>)

In [38]:
model.layers

In [39]:
print(model.name)
print(model.name_scope())

sequential
sequential
