In [1]:
import numpy as np


def softmax(x):
    # x 为数组
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    sm_x = exp_x / sum_exp_x
    return sm_x


x = np.array([10, 3, 40, 4])
softmax(x)

array([9.35762297e-14, 8.53304763e-17, 1.00000000e+00, 2.31952283e-16])

In [3]:
x = np.array([10, 2, 10000, 4])
print(softmax(x))

# 计算 e^x 时,产生了溢出

[ 0.  0. nan  0.]


/home/yangbin7/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in exp
  
/home/yangbin7/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  


In [4]:
def softmax(x):
    max_x = np.max(x)
    exp_x = np.exp(x - max_x)  # 减去最大值,防止溢出
    sum_exp_x = np.sum(exp_x)
    sm_x = exp_x / sum_exp_x
    return sm_x


x = np.array([10, 2, 10000, 4])
print(softmax(x))

[0. 0. 1. 0.]


In [ ]:
# Log Softmax

In [5]:
x = np.array([10, 2, 10000, 4])
np.log(softmax(x))

# 计算 log(0) 时出现了下溢出

/home/yangbin7/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([-inf, -inf,   0., -inf])

In [6]:
def logsoftmax(x, recover_probs=True):
    # LogSoftMax Implementation
    max_x = np.max(x)
    exp_x = np.exp(x - max_x)
    sum_exp_x = np.sum(exp_x)
    log_sum_exp_x = np.log(sum_exp_x)
    max_plus_log_sum_exp_x = max_x + log_sum_exp_x
    log_probs = x - max_plus_log_sum_exp_x

    # Recover probs
    if recover_probs:
        exp_log_probs = np.exp(log_probs)
        sum_log_probs = np.sum(exp_log_probs)
        probs = exp_log_probs / sum_log_probs
        return probs

    return log_probs


x = np.array([10, 2, 10000, 4])
print(logsoftmax(x, recover_probs=True))

[0. 0. 1. 0.]


In [ ]:
# Softmax Temperature

In [10]:
x = np.array([38, 20, 40, 39])
softmax(x).round(2)

array([0.09, 0.  , 0.67, 0.24])

In [11]:
softmax(x / 0.001)

array([0., 0., 1., 0.])

In [13]:
softmax(x / 100).round(2)

array([0.26, 0.22, 0.26, 0.26])