# 数据索引与选择

In [3]:
import pandas as pd
import numpy as np

## 索引Series对象

In [4]:
# Series 作为词典对象

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data["b"]

0.5

In [5]:
#  in 操作
'a' in data  

True

In [6]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [9]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 赋值以扩展对象
data['e'] = 1000.00
data

a       0.25
b       0.50
c       0.75
d       1.00
e    1000.00
dtype: float64

In [12]:
# 赋值以更改对象
data['b'] = 10000
data

a        0.25
b    10000.00
c        0.75
d        1.00
e     1000.00
dtype: float64

In [13]:
# 作为 Numpy 数组
# 通过显式定义的索引来切片，
data['a':'c']

a        0.25
b    10000.00
c        0.75
dtype: float64

In [14]:
# 通过隐含的 自然数 索引来切片
data[0:2]  

a        0.25
b    10000.00
dtype: float64

>**注意**：
- 显式索引切片时，`data['a':'c']`，<span class="burk">最后的索引 'c' 是包含在内的</span>
- 隐含的整数索引切片时，`data[0:2]`，最后的索引`2`是不包含在内的

In [15]:
# masking 掩码
data[(data > 0.3) & (data < 0.8)]  

c    0.75
dtype: float64

In [16]:
# fancy indexing
data[['a', 'e']]

a       0.25
e    1000.00
dtype: float64

In [17]:
# 与上式相比
data['a', 'e']  

KeyError: ('a', 'e')

## 索引属性: `loc,  iloc, ix`
- `loc`属性索引时指向显式定义的索引
- `iloc`属性索引时，指向 Python 列表风格的自然数索引

In [18]:
data = pd.Series(['a', 'b', 'c', 'ff', 'gg'], index=[1, 3, 50, 11, 13])
data

1      a
3      b
50     c
11    ff
13    gg
dtype: object

In [19]:
data[1]  # 显式索引

'a'

In [20]:
data[1:3]  # 隐式的自然数索引

3     b
50    c
dtype: object

In [23]:
data.loc[50]  # 显式索引

'c'

In [22]:
data.loc[2] # 显式索引

KeyError: 2

In [24]:
data.loc[50:13] # 显式索引，末尾索引是包含在内的

50     c
11    ff
13    gg
dtype: object

In [25]:
data.iloc[1:3] # 隐式索引

3     b
50    c
dtype: object

In [26]:
data.iloc[1] # 隐式索引

'b'

## DataFrame数据选择
> **DataFrame 的基本索引是列索引**

### DataFrame 作为词典


In [27]:

area = pd.Series({
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
})
pop = pd.Series({
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
})
data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [28]:
data['area']  # 词典键-值

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [29]:
data.area  # 属性访问方式

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

>- **列名与DataFrame对象的属性冲突时**，就不能使用属性访问方式
- 应尽量避免属性赋值方式，来改变对象：使用`data['pop'] = z`，而不是`data.pop = z`

In [30]:
data.area is data['area']

True

In [31]:
data.pop is data['pop']

False

In [32]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [33]:
#  添加新列
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### DataFrame 值为数组

In [34]:
data.values  

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [35]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [36]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [37]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [38]:
data.iloc[:3, :2]  # 直接 data[:3,:2] 会出错！！！

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [39]:
data.loc[:'Illinois', :'pop']  #  使用显示索引及列名

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [40]:
data.loc[data.density > 100, ['pop', 'density']]  # 掩码及 fancy indexing

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [41]:
data.iloc[0, 2] = 90  # 变更
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763